### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by javaand** [NetHome/ZWave#1]
Hi @stefangs 
Could you please provide me an explanation to how get the following output:
> AddNode ANY
> {"AddNode.Event": {"status": "LEARN_READY", "node": 0}}
> {"AddNode.Event": {"status": "NODE_FOUND", "node": 0}}
> {"AddNode.Event": {"status": "ADDING_SLAVE", "node": 8}}
> {"AddNode.Event": {"status": "PROTOCOL_DONE", "node": 8}}
> AddNode STOP
> {"AddNode.Event": {"status": "DONE", "node": 8}}
> SwitchBinary.Set 8 1
> {"SendData.Response": {"callbackId": 1, "status": -1}}
Thanks in advance

**Comment by stefangs** [comment]
Yes, the documentation was a bit thin on how to do this. I have added some more documentation now. See the updated README-file.
