### ISSUE TITLE
interactive session

### ISSUE THREAD

**Issue by javaand** [NetHome/ZWave#2]
Hi @stefangs 
Please could you provide me a way to use the interactive session

thanks in advance

**Comment by stefangs** [comment]
Sure, I added instruction is the readme on how to run the jar in interactive mode from the command line. Hope this helps!

**Comment by halil-raso** [comment]
Thanks @stefangs 
after your answer I checked shell.java and I realized that it is a main class. 
to run it we need serial port name. You mentioned in the readme file COM7 
and my port name is /dev/ttyACM0 but in both case (COM7 and /dev/ttyACM0) I get no such port exception.

**Comment by halil-raso** [comment]
Finally It worked but when typing 
in the terminal the following
AddNode ANY
I get the following output:
{"AddNode.Event": {"status": "FAILED", "node": 0}}
Thanks in advance.
