### ISSUE TITLE
AddNode Problem

### ISSUE THREAD

**Issue by halil-raso** [NetHome/ZWave#3]
Hi @stefangs 
when typing AddNode ANY for first time I get 
{"AddNode.Event": {"status": "FAILED", "node": 0}}
but when typing AddNode Stop and then AddNode ANY
I get the following output:
{"AddNode.Event": {"status": "LEARN_READY", "node": 0}} and no more than that

**Comment by halil-raso** [comment]
For testing purpose I use Smart energy switch.

**Comment by stefangs** [comment]
When give the command "AddNode ANY", you set the ZWave interface in "inclusion mode", meaning it is ready to accept new nodes into the network. What you then have to do is to actually include a new node. How you do that differs between different devices, but normally you have to press an include button on the device or press the button three times in a row or something similar. The device must not already belong to a network, so it is free to join this. You will have to consult the manual for your smart energy switch on how to trigger it to join the ZWave network.

**Comment by halil-raso** [comment]
Thanks @stefangs 
I chnaged my smart energy switch and it works fine.
Thanks again.
